### ISSUE TITLE
Migrations cannot be rolled back

### ISSUE THREAD

**Issue by melvyn-apryl** [Opus10/django-pghistory#18]
Since the triggers are inserted without the use of the migrations system, once the table gets removed, the context tries to reinsert the triggers, which now reference tables which have been removed (at least, that's my analysis):

```
  Unapplying core.0057_reimbursementclaim_reimbursementclaimhistory_reimbursementremovals... OK
Traceback (most recent call last):
  File ".../site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File ".../site-packages/pgconnection/core.py", line 85, in execute
    return super().execute(sql, args)
psycopg2.errors.UndefinedTable: relation "core_reimbursementclaim" does not exist
CONTEXT:  SQL statement "CREATE TRIGGER pgtrigger_ReimbursementClaim_updates_insert_3607b
                    AFTER INSERT ON core_reimbursementclaim
                    
                    FOR EACH ROW 
                    EXECUTE PROCEDURE pgtrigger_ReimbursementClaim_updates_insert_3607b()"
PL/pgSQL function inline_code_block line 2 at SQL statement


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    main()
  File "manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File ".../site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File ".../site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File ".../site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File ".../site-packages/django/core/management/commands/migrate.py", line 268, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File ".../site-packages/django/core/management/sql.py", line 54, in emit_post_migrate_signal
    **kwargs
  File ".../site-packages/django/dispatch/dispatcher.py", line 179, in send
    for receiver in self._live_receivers(sender)
  File ".../site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
    for receiver in self._live_receivers(sender)
  File ".../site-packages/pgtrigger/apps.py", line 9, in install
    pgtrigger.install(database=using)
  File ".../site-packages/pgtrigger/core.py", line 903, in install
    trigger.install(model)
  File ".../site-packages/pgtrigger/core.py", line 657, in install
    cursor.execute(rendered_trigger)
  File ".../site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File ".../site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File ".../site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File ".../site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File ".../site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File ".../site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File ".../site-packages/pgconnection/core.py", line 85, in execute
    return super().execute(sql, args)
django.db.utils.ProgrammingError: relation "core_reimbursementclaim" does not exist
CONTEXT:  SQL statement "CREATE TRIGGER pgtrigger_ReimbursementClaim_updates_insert_3607b
                    AFTER INSERT ON core_reimbursementclaim
                    
                    FOR EACH ROW 
                    EXECUTE PROCEDURE pgtrigger_ReimbursementClaim_updates_insert_3607b()"
PL/pgSQL function inline_code_block line 2 at SQL statement

```

A fix seems to be possible if my analysis is correct, since the [post_migrate signal](https://docs.djangoproject.com/en/3.2/ref/signals/#post-migrate) has a "plan" argument:

>The migration plan that was used for the migration run. While the plan is not public API, this allows for the rare cases when it is necessary to know the plan. A plan is a list of two-tuples with the first item being the instance of a migration class and the second item showing if the migration was rolled back (True) or applied (False).

If the 2nd member of the tuple is True, we should not reinsert the triggers, since the triggers are cleaned up successfully using cascade:
```
% djmanage sqlmigrate --backwards core 0057
BEGIN;
--
-- Create model ReimbursementClaimHistory
--
DROP TABLE "core_reimbursementclaimhistory" CASCADE;
--
-- Create model ReimbursementRemovals
--
DROP TABLE "core_reimbursementremovals" CASCADE;
--
-- Create model ReimbursementClaim
--
DROP TABLE "core_reimbursementclaim" CASCADE;
COMMIT;
```

**Comment by melvyn-oviavo** [comment]
Just noticed that unapplying succeeded as far as the migration system is concerned, but the triggers are still there. Reapplying the migration does not give any issues.

Unfortunately, lack the time at the moment to see what happens if I then change the table names. Do I end up with 6 triggers or 3?

**Comment by wesleykendall** [comment]
@melvyn-apryl [django-pgtrigger](https://github.com/Opus10/django-pgtrigger) now supports the django migration system, which solves this particular issue

Although I kept the legacy `post_migrate` system around, I wasn't planning to change it's behavior and instead encourage users to upgrade django-pgtrigger.

Some instructions for upgrading django-pghistory to support the latest django-pgtrigger are at https://github.com/Opus10/django-pghistory/issues/43
